/**
 * Feature engineering — MIRRORS `ml/features.py` EXACTLY (REQUIREMENTS §7).
 *
 * ⚠️  This file and `ml/features.py` are two implementations of one spec. When
 * they drift, the app produces confidently wrong predictions with no error and
 * nothing crashes. That is why §15.1's parity test is blocking: it replays
 * fixtures generated by the Python side and asserts all 95 features and the
 * final probability agree to 1e-6.
 *
 * Change one side, change the other in the same commit, and regenerate the
 * fixtures with `python ml/export.py`.
 *
 * Feature names stay snake_case here (§16: ML feature names are snake_case in
 * both languages). The camelCase boundary lives in `src/db/queries.ts`.
 */

// --------------------------------------------------------------------------
// §7.1 Base variables
// --------------------------------------------------------------------------

export const SELF_VARS = [
  'severity',
  'itch',
  'stress',
  'sleep_hours',
  'water_glasses',
  'alcohol_units',
  'diet_dairy',
  'diet_gluten',
  'diet_processed',
  'diet_sugar',
  'diet_red_meat',
  'illness',
  'sore_throat',
  'skin_injury',
] as const;

export const ENV_VARS = [
  'temp_mean_c',
  'humidity_mean_pct',
  'dew_point_c',
  'pressure_hpa',
  'uv_index_max',
  'precipitation_mm',
  'pm2_5',
  'pollen_total',
] as const;

export const WEARABLE_VARS = ['sleep_hours_device', 'resting_hr', 'steps'] as const;

export const BASE_VARS: readonly string[] = [...SELF_VARS, ...ENV_VARS, ...WEARABLE_VARS];

// --------------------------------------------------------------------------
// §7.3 Lag and rolling specification
// --------------------------------------------------------------------------

export const LAG_VARS = [
  'stress',
  'sleep_hours',
  'itch',
  'alcohol_units',
  'diet_dairy',
  'diet_processed',
  'diet_sugar',
  'illness',
  'sore_throat',
  'skin_injury',
  'temp_delta_1d',
  'humidity_delta_1d',
  'pressure_delta_1d',
  'uv_index_max',
  'pm2_5',
  'pollen_total',
  'humidity_mean_pct',
] as const;

export const LAGS = [1, 3, 7, 14] as const;

export const ROLL_VARS = [
  'stress',
  'sleep_hours',
  'itch',
  'alcohol_units',
  'uv_index_max',
  'pm2_5',
  'humidity_mean_pct',
] as const;

export const ROLL_WINDOWS = [3, 7, 14] as const;

export const CURRENT_VARS = [
  'severity_baseline',
  'severity_delta',
  'sleep_debt_7d',
  'temp_mean_c',
  'humidity_mean_pct',
  'uv_index_max',
] as const;

/**
 * Non-missing observations a window needs before it yields a value.
 * Hardcoded rather than derived from ceil(0.6 * w) so the two languages cannot
 * disagree about a float boundary.
 */
const MIN_PERIODS: Readonly<Record<number, number>> = { 3: 2, 7: 5, 14: 9 };

/** §7.5.1 forward-fill horizon, in days. */
export const FFILL_LIMIT = 3;

/** §7.5.3 refuse to predict past this much missing recent data. */
export const MAX_MISSING_FRACTION = 0.4;
export const RECENT_WINDOW = 14;

/** §8.6 min_days_required. */
export const MIN_HISTORY_DAYS = 14;

const BASELINE_WINDOW = 14;
const SLEEP_TARGET_HOURS = 7.5;
const SLEEP_DEBT_WINDOW = 7;

export function featureNames(): string[] {
  const names: string[] = [];
  for (const v of LAG_VARS) for (const l of LAGS) names.push(`${v}_lag${l}`);
  for (const v of ROLL_VARS) for (const w of ROLL_WINDOWS) names.push(`${v}_roll${w}`);
  names.push(...CURRENT_VARS);
  return names;
}

export const FEATURE_NAMES: readonly string[] = featureNames();

// --------------------------------------------------------------------------
// Input shape
// --------------------------------------------------------------------------

/**
 * One calendar day, already joined across checkin/environment/wearable.
 * Snake-case because these are ML variable names, not UI properties.
 */
export interface FeatureInputRow {
  readonly date: string; // 'YYYY-MM-DD', user's local calendar day
  readonly [column: string]: string | number | null | undefined;
}

export type Series = (number | null)[];

export interface BaseFrame {
  readonly dates: readonly string[];
  readonly columns: Readonly<Record<string, Series>>;
  /** 1 where the user actually logged a check-in, taken before any filling. */
  readonly hasCheckin: readonly number[];
}

export type FeatureVector = Record<string, number | null>;

// --------------------------------------------------------------------------
// Date helpers — 'YYYY-MM-DD' arithmetic with no timezone in play
// --------------------------------------------------------------------------

const MS_PER_DAY = 86_400_000;

function toUtcMillis(date: string): number {
  const [y, m, d] = date.split('-').map(Number);
  return Date.UTC(y, m - 1, d);
}

function fromUtcMillis(millis: number): string {
  const dt = new Date(millis);
  const month = `${dt.getUTCMonth() + 1}`.padStart(2, '0');
  const day = `${dt.getUTCDate()}`.padStart(2, '0');
  return `${dt.getUTCFullYear()}-${month}-${day}`;
}

export function addDays(date: string, days: number): string {
  return fromUtcMillis(toUtcMillis(date) + days * MS_PER_DAY);
}

export function daysBetween(from: string, to: string): number {
  return Math.round((toUtcMillis(to) - toUtcMillis(from)) / MS_PER_DAY);
}

// --------------------------------------------------------------------------
// Series primitives — each mirrors one pandas operation
// --------------------------------------------------------------------------

/** pandas `Series.shift(n)`. */
function shift(series: Series, n: number): Series {
  return series.map((_, i) => (i - n >= 0 ? series[i - n] : null));
}

/** pandas `Series.ffill(limit)` — carry the last value forward at most `limit` rows. */
function forwardFill(series: Series, limit: number): Series {
  const out: Series = new Array(series.length).fill(null);
  let last: number | null = null;
  let filled = 0;
  for (let i = 0; i < series.length; i += 1) {
    const value = series[i];
    if (value !== null) {
      out[i] = value;
      last = value;
      filled = 0;
    } else if (last !== null && filled < limit) {
      out[i] = last;
      filled += 1;
    } else {
      out[i] = null;
    }
  }
  return out;
}

/**
 * pandas `Series.rolling(window, min_periods).mean()` — trailing window ending
 * at i inclusive, missing values skipped, null until `minPeriods` are present.
 */
function rollingMean(series: Series, window: number, minPeriods: number): Series {
  const out: Series = new Array(series.length).fill(null);
  for (let i = 0; i < series.length; i += 1) {
    let sum = 0;
    let count = 0;
    for (let j = Math.max(0, i - window + 1); j <= i; j += 1) {
      const value = series[j];
      if (value !== null) {
        sum += value;
        count += 1;
      }
    }
    out[i] = count >= minPeriods ? sum / count : null;
  }
  return out;
}

/** pandas `Series.rolling(window, min_periods=window).sum()`. */
function rollingSumComplete(series: Series, window: number): Series {
  const out: Series = new Array(series.length).fill(null);
  for (let i = 0; i < series.length; i += 1) {
    if (i + 1 < window) continue;
    let sum = 0;
    let complete = true;
    for (let j = i - window + 1; j <= i; j += 1) {
      const value = series[j];
      if (value === null) {
        complete = false;
        break;
      }
      sum += value;
    }
    out[i] = complete ? sum : null;
  }
  return out;
}

function difference(series: Series): Series {
  return series.map((value, i) => {
    if (i === 0) return null;
    const previous = series[i - 1];
    return value === null || previous === null ? null : value - previous;
  });
}

function subtract(a: Series, b: Series): Series {
  return a.map((value, i) => {
    const other = b[i];
    return value === null || other === null ? null : value - other;
  });
}

function toNumber(value: string | number | null | undefined): number | null {
  if (value === null || value === undefined || value === '') return null;
  const n = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(n) ? n : null;
}

// --------------------------------------------------------------------------
// Base frame assembly
// --------------------------------------------------------------------------

/**
 * Join-and-clean: one row per calendar date with gaps materialised.
 *
 * Dates absent from `rows` are inserted as all-missing days so lags count
 * calendar days rather than row positions — a user who skips a week must not
 * have `stress_lag7` silently reach back a fortnight.
 */
export function buildBaseFrame(rows: readonly FeatureInputRow[]): BaseFrame {
  if (rows.length === 0) {
    return { dates: [], columns: {}, hasCheckin: [] };
  }

  const sorted = [...rows].sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
  const byDate = new Map<string, FeatureInputRow>();
  for (const row of sorted) byDate.set(row.date, row);

  const first = sorted[0].date;
  const last = sorted[sorted.length - 1].date;
  const span = daysBetween(first, last);

  const dates: string[] = [];
  for (let i = 0; i <= span; i += 1) dates.push(addDays(first, i));

  const columns: Record<string, Series> = {};
  for (const name of BASE_VARS) {
    columns[name] = dates.map((date) => toNumber(byDate.get(date)?.[name]));
  }

  // Taken before any filling so the §7.5.3 guard sees the real gaps.
  const hasCheckin = columns.severity.map((value) => (value === null ? 0 : 1));

  // HD-5: where both exist for a date, the wearable sleep value wins.
  const deviceSleep = columns.sleep_hours_device;
  columns.sleep_hours = columns.sleep_hours.map((value, i) =>
    deviceSleep[i] !== null ? deviceSleep[i] : value,
  );

  // §7.5.1 forward-fill every base variable across at most 3 consecutive days.
  for (const name of BASE_VARS) {
    columns[name] = forwardFill(columns[name], FFILL_LIMIT);
  }

  addDerived(columns);
  return { dates, columns, hasCheckin };
}

/** §7.2 derived variables. Computed after filling, before lagging. */
function addDerived(columns: Record<string, Series>): void {
  columns.temp_delta_1d = difference(columns.temp_mean_c);
  columns.humidity_delta_1d = difference(columns.humidity_mean_pct);
  columns.pressure_delta_1d = difference(columns.pressure_hpa);

  // All 7 nights required: a partial sum would overstate the debt.
  const slept = rollingSumComplete(columns.sleep_hours, SLEEP_DEBT_WINDOW);
  columns.sleep_debt_7d = slept.map((total) =>
    total === null ? null : Math.max(0, SLEEP_DEBT_WINDOW * SLEEP_TARGET_HOURS - total),
  );

  columns.severity_baseline = rollingMean(
    columns.severity,
    BASELINE_WINDOW,
    MIN_PERIODS[BASELINE_WINDOW],
  );
  columns.severity_delta = subtract(columns.severity, columns.severity_baseline);
}

// --------------------------------------------------------------------------
// Feature matrix
// --------------------------------------------------------------------------

/** Expand a base frame into the 95 feature series (§7.3). */
export function buildFeatureSeries(base: BaseFrame): Record<string, Series> {
  const out: Record<string, Series> = {};
  const empty: Series = base.dates.map(() => null);

  for (const v of LAG_VARS) {
    const series = base.columns[v] ?? empty;
    for (const l of LAGS) out[`${v}_lag${l}`] = shift(series, l);
  }
  for (const v of ROLL_VARS) {
    const series = base.columns[v] ?? empty;
    for (const w of ROLL_WINDOWS) out[`${v}_roll${w}`] = rollingMean(series, w, MIN_PERIODS[w]);
  }
  for (const v of CURRENT_VARS) {
    out[v] = base.columns[v] ?? empty;
  }
  return out;
}

/** Fraction of the trailing 14 calendar days carrying a real check-in. */
export function recentCheckinCoverage(base: BaseFrame, index: number): number {
  const start = Math.max(0, index - RECENT_WINDOW + 1);
  let sum = 0;
  for (let i = start; i <= index; i += 1) sum += base.hasCheckin[i];
  return sum / (index - start + 1);
}

/** §7.5.3 guard: too much of the recent window missing means no prediction. */
export function canPredict(base: BaseFrame, index: number): boolean {
  return recentCheckinCoverage(base, index) >= 1 - MAX_MISSING_FRACTION;
}

export interface LatestFeatures {
  readonly vector: FeatureVector;
  /** False when §7.5.3 says there is not enough recent data to score. */
  readonly canPredict: boolean;
  /** Distinct days the user has actually logged, for the FR-4.2 progress state. */
  readonly checkinDays: number;
  readonly date: string | null;
}

/**
 * Features for the most recent date in `rows` — the vector the scorer consumes.
 * Mirrors `features.latest_feature_vector` in Python.
 */
export function latestFeatureVector(rows: readonly FeatureInputRow[]): LatestFeatures {
  const base = buildBaseFrame(rows);
  if (base.dates.length === 0) {
    return { vector: {}, canPredict: false, checkinDays: 0, date: null };
  }

  const series = buildFeatureSeries(base);
  const index = base.dates.length - 1;
  const vector: FeatureVector = {};
  for (const name of FEATURE_NAMES) {
    vector[name] = series[name][index] ?? null;
  }

  return {
    vector,
    canPredict: canPredict(base, index),
    checkinDays: base.hasCheckin.reduce<number>((total, flag) => total + flag, 0),
    date: base.dates[index],
  };
}
